version: 2.1
orbs:
  node: circleci/node@4.2.0
  
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-

      - run: npm install

  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: docker build
          command: docker build -t docker.io/$NAMESPACE/client:${CIRCLE_BRANCH#*/} .
      - run:
          name: docker login
          command: |
           docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
           docker push docker.io/$NAMESPACE/client:${CIRCLE_BRANCH#*/}

workflows:
  main:
    jobs:
      - build-and-test
      - docker-build
