version: 2.1
orbs:
  node: circleci/node@3.0.0
  
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - run: npm install

  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: docker build -t docker.io/$NAMESPACE/client:${CIRCLE_BRANCH#*/} .
      - run:
          name: docker login
          command: |
           docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
           docker push docker.io/$NAMESPACE/client:${CIRCLE_BRANCH#*/}

workflows:
  main:
    jobs:
      - build-and-test
      - docker-build
