version: 2.1
orbs:
  node: circleci/node@4.2.0
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - package.json
            - public
            - src
            - dockerfile
            - nginx.conf
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - sonarcloud/scan

  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: docker build -t docker.io/$NAMESPACE/client:${CIRCLE_BRANCH#*/} .
      - run:
          name: docker login
          command: |
            docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
            docker push docker.io/$NAMESPACE/client:${CIRCLE_BRANCH#*/}

workflows:
  main:
    jobs:
      - build-and-test
      - docker-build
